services:
  - type: web
    name: nusi-membership
    runtime: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: API_KEY
        generateValue: true
      - key: MAX_CONCURRENT_DG
        value: "1"
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: SPREADSHEET_ID
        value: "1BCovd-XYwFto5oelzmgDvYjCNpQ45WP1pFk7Xd0Fqok"
      - key: SHEET_NAME
        value: "Sheet1"
      - key: MAIN_FOLDER_ID
        value: "13UBnaaMa27-qTf6NvBXe5Vt6jkCCYFaZ"
      - key: SLIDER_FOLDER_ID
        value: "1tZp5paf-Vju9w1e2Z4naKHQ3VKu-KFcM"
